### ISSUE TITLE
Вопрос с байтами и оффсетами

### ISSUE THREAD

**Issue by djdejawu** [Galavarez/Data_Frog_Y2_Hd_Plus#1]
тут немного не ясно...
хочу переписать оное на питоне для своих автогенерилок, и что-то по оффсетам и размерам файлов не совпадает.
На части файл делится - это ясно.
512...515 - это 4 байта (в хекс 0х200...0x203)
А в коде читаем длина - 7.
```
    // Получам размер png
    FS := TFileStream.Create(path_zes, fmOpenRead);
    FS.Position:= 512;
    FS.Read(buffer_size_png, 7);
    // Получам массив байт png
    FS.Position:= 520;
    FS.Read(buffer_file_png, buffer_size_png);
    FS.Free;
```
И я на сколько понял, байты эти записаны в little endian. (facepalm)

**Comment by Galavarez** [comment]
> А в коде читаем длина - 7.

по всей видимости ошибка =)
buffer_size_png тип LongInt -- а это 4 байта

>  И я на сколько понял, байты эти записаны в little endian. (facepalm)

little-endian ну да а как иначе, это же стандарт для х86

**Comment by djdejawu** [comment]
Благодарю! Разобрался и написал консольник [zesfrogger](https://github.com/djdejawu/zesfrogger)
